package com.tamuvii.dao;

import com.tamuvii.model.Actor;

/**
 * DAO interface for table: Actor.
 * @author autogenerated
 */
public interface ActorDao extends GenericDao<Actor, Integer>  {
	// constructor only
}

