package com.tamuvii.dao;

import com.tamuvii.model.Config;
import com.tamuvii.model.ConfigExample;
import java.util.List;

public interface ConfigDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table config
	 * @ibatorgenerated
	 */
	int countByExample(ConfigExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table config
	 * @ibatorgenerated
	 */
	int deleteByExample(ConfigExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table config
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(String configkey);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table config
	 * @ibatorgenerated
	 */
	void insert(Config record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table config
	 * @ibatorgenerated
	 */
	void insertSelective(Config record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table config
	 * @ibatorgenerated
	 */
	List selectByExample(ConfigExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table config
	 * @ibatorgenerated
	 */
	Config selectByPrimaryKey(String configkey);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table config
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Config record, ConfigExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table config
	 * @ibatorgenerated
	 */
	int updateByExample(Config record, ConfigExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table config
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Config record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table config
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(Config record);
}