package com.tamuvii.dao;

import com.tamuvii.model.Director;

/**
 * DAO interface for table: Director.
 * @author autogenerated
 */
public interface DirectorDao extends GenericDao<Director, Integer>  {
	// constructor only
}

