package com.tamuvii.dao;

import com.tamuvii.model.Director;
import com.tamuvii.model.DirectorExample;
import java.util.List;

public interface DirectorDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	int countByExample(DirectorExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	int deleteByExample(DirectorExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer director);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	void insert(Director record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	void insertSelective(Director record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	List selectByExample(DirectorExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	Director selectByPrimaryKey(Integer director);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Director record, DirectorExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	int updateByExample(Director record, DirectorExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Director record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(Director record);
}