package com.tamuvii.dao;

import java.io.Serializable;

import com.tamuvii.model.Genre;

/**
 * DAO interface for table: Genre.
 * @author autogenerated
 */
public interface GenreDao extends GenericDao<Genre, Serializable>  {
	// constructor only
}

