package com.tamuvii.dao;

import java.io.Serializable;

import com.tamuvii.model.LocalizedData;

/**
 * DAO interface for table: LocalizedData.
 * @author autogenerated
 */
public interface LocalizedDataDao extends GenericDao<LocalizedData, Serializable>  {
	// constructor only
}

