package com.tamuvii.dao;

import com.tamuvii.model.Mark;

/**
 * DAO interface for table: Mark.
 * @author autogenerated
 */
public interface MarkDao extends GenericDao<Mark, String>  {
	// constructor only
}

