package com.tamuvii.dao;

import java.io.Serializable;
import java.util.List;

import com.tamuvii.model.Movie;

/**
 * DAO interface for table: Movie.
 * @author autogenerated
 */
public interface MovieDao extends GenericDao<Movie, Serializable>  {
	
	public List<Movie> findMovieByFilter(String filter);
	
}