package com.tamuvii.dao;

import java.io.Serializable;

import com.tamuvii.model.Movie;

/**
 * DAO interface for table: Movie.
 * @author autogenerated
 */
public interface MovieDao extends GenericDao<Movie, Serializable>  {
	// constructor only
}

