package com.tamuvii.dao;

import com.tamuvii.model.Movie;

/**
 * DAO interface for table: Movie.
 * @author autogenerated
 */
public interface MovieDao extends GenericDao<Movie, Integer>  {
	// constructor only
}

