package com.tamuvii.dao;

import com.tamuvii.model.Movie;
import com.tamuvii.model.MovieExample;
import java.util.List;

public interface MovieDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	int countByExample(MovieExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	int deleteByExample(MovieExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer movie);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	void insert(Movie record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	void insertSelective(Movie record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	List selectByExample(MovieExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	Movie selectByPrimaryKey(Integer movie);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Movie record, MovieExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	int updateByExample(Movie record, MovieExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Movie record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(Movie record);
}