package com.tamuvii.dao;

import com.tamuvii.model.Opinion;
import com.tamuvii.model.OpinionExample;
import java.util.List;

public interface OpinionDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	int countByExample(OpinionExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	int deleteByExample(OpinionExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer opinion);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	void insert(Opinion record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	void insertSelective(Opinion record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	List selectByExample(OpinionExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	Opinion selectByPrimaryKey(Integer opinion);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Opinion record, OpinionExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	int updateByExample(Opinion record, OpinionExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Opinion record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(Opinion record);
}