package com.tamuvii.dao;

import java.io.Serializable;

import com.tamuvii.model.Opinion;

/**
 * DAO interface for table: Opinion.
 * @author autogenerated
 */
public interface OpinionDao extends GenericDao<Opinion, Serializable>  {
	// constructor only
}

