package com.tamuvii.dao;

import com.tamuvii.model.Review;
import com.tamuvii.model.ReviewExample;
import java.util.List;

public interface ReviewDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	int countByExample(ReviewExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	int deleteByExample(ReviewExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer review);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	void insert(Review record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	void insertSelective(Review record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	List selectByExample(ReviewExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	Review selectByPrimaryKey(Integer review);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Review record, ReviewExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	int updateByExample(Review record, ReviewExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Review record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(Review record);
}