package com.tamuvii.dao;

import java.io.Serializable;

import com.tamuvii.model.Review;

/**
 * DAO interface for table: Review.
 * @author autogenerated
 */
public interface ReviewDao extends GenericDao<Review, Serializable>  {
	// constructor only
}

