package com.tamuvii.dao;

import com.tamuvii.model.Title;

/**
 * DAO interface for table: Title.
 * @author autogenerated
 */
public interface TitleDao extends GenericDao<Title, String>  {
	// constructor only
}

