package com.tamuvii.dao;

import com.tamuvii.model.UserReviewVoteExample;
import com.tamuvii.model.UserReviewVoteKey;
import java.util.List;
import com.tamuvii.model.UserReviewVote;

public interface UserReviewVoteDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	int countByExample(UserReviewVoteExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	int deleteByExample(UserReviewVoteExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(UserReviewVoteKey key);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	void insert(UserReviewVote record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	void insertSelective(UserReviewVote record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	List selectByExample(UserReviewVoteExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	UserReviewVote selectByPrimaryKey(UserReviewVoteKey key);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(UserReviewVote record,
			UserReviewVoteExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	int updateByExample(UserReviewVote record, UserReviewVoteExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(UserReviewVote record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(UserReviewVote record);
}