package com.tamuvii.dao;

import com.tamuvii.model.UserToUser;
import com.tamuvii.model.UserToUserExample;
import com.tamuvii.model.UserToUserKey;
import java.util.List;

public interface UserToUserDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_to_user
     *
     * @ibatorgenerated
     */
    int countByExample(UserToUserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_to_user
     *
     * @ibatorgenerated
     */
    int deleteByExample(UserToUserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_to_user
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(UserToUserKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_to_user
     *
     * @ibatorgenerated
     */
    void insert(UserToUser record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_to_user
     *
     * @ibatorgenerated
     */
    void insertSelective(UserToUser record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_to_user
     *
     * @ibatorgenerated
     */
    List selectByExample(UserToUserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_to_user
     *
     * @ibatorgenerated
     */
    UserToUser selectByPrimaryKey(UserToUserKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_to_user
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(UserToUser record, UserToUserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_to_user
     *
     * @ibatorgenerated
     */
    int updateByExample(UserToUser record, UserToUserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_to_user
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(UserToUser record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_to_user
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(UserToUser record);
}