package com.tamuvii.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AppUserExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table app_user
	 * @ibatorgenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table app_user
	 * @ibatorgenerated
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table app_user
	 * @ibatorgenerated
	 */
	public AppUserExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table app_user
	 * @ibatorgenerated
	 */
	protected AppUserExample(AppUserExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table app_user
	 * @ibatorgenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table app_user
	 * @ibatorgenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table app_user
	 * @ibatorgenerated
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table app_user
	 * @ibatorgenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table app_user
	 * @ibatorgenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table app_user
	 * @ibatorgenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table app_user
	 * @ibatorgenerated
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table app_user
	 * @ibatorgenerated
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return this;
		}

		public Criteria andUsernameIn(List values) {
			addCriterion("username in", values, "username");
			return this;
		}

		public Criteria andUsernameNotIn(List values) {
			addCriterion("username not in", values, "username");
			return this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return this;
		}

		public Criteria andVersionIn(List values) {
			addCriterion("version in", values, "version");
			return this;
		}

		public Criteria andVersionNotIn(List values) {
			addCriterion("version not in", values, "version");
			return this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return this;
		}

		public Criteria andPasswordIn(List values) {
			addCriterion("password in", values, "password");
			return this;
		}

		public Criteria andPasswordNotIn(List values) {
			addCriterion("password not in", values, "password");
			return this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return this;
		}

		public Criteria andFirstnameIsNull() {
			addCriterion("first_name is null");
			return this;
		}

		public Criteria andFirstnameIsNotNull() {
			addCriterion("first_name is not null");
			return this;
		}

		public Criteria andFirstnameEqualTo(String value) {
			addCriterion("first_name =", value, "firstname");
			return this;
		}

		public Criteria andFirstnameNotEqualTo(String value) {
			addCriterion("first_name <>", value, "firstname");
			return this;
		}

		public Criteria andFirstnameGreaterThan(String value) {
			addCriterion("first_name >", value, "firstname");
			return this;
		}

		public Criteria andFirstnameGreaterThanOrEqualTo(String value) {
			addCriterion("first_name >=", value, "firstname");
			return this;
		}

		public Criteria andFirstnameLessThan(String value) {
			addCriterion("first_name <", value, "firstname");
			return this;
		}

		public Criteria andFirstnameLessThanOrEqualTo(String value) {
			addCriterion("first_name <=", value, "firstname");
			return this;
		}

		public Criteria andFirstnameLike(String value) {
			addCriterion("first_name like", value, "firstname");
			return this;
		}

		public Criteria andFirstnameNotLike(String value) {
			addCriterion("first_name not like", value, "firstname");
			return this;
		}

		public Criteria andFirstnameIn(List values) {
			addCriterion("first_name in", values, "firstname");
			return this;
		}

		public Criteria andFirstnameNotIn(List values) {
			addCriterion("first_name not in", values, "firstname");
			return this;
		}

		public Criteria andFirstnameBetween(String value1, String value2) {
			addCriterion("first_name between", value1, value2, "firstname");
			return this;
		}

		public Criteria andFirstnameNotBetween(String value1, String value2) {
			addCriterion("first_name not between", value1, value2, "firstname");
			return this;
		}

		public Criteria andLastnameIsNull() {
			addCriterion("last_name is null");
			return this;
		}

		public Criteria andLastnameIsNotNull() {
			addCriterion("last_name is not null");
			return this;
		}

		public Criteria andLastnameEqualTo(String value) {
			addCriterion("last_name =", value, "lastname");
			return this;
		}

		public Criteria andLastnameNotEqualTo(String value) {
			addCriterion("last_name <>", value, "lastname");
			return this;
		}

		public Criteria andLastnameGreaterThan(String value) {
			addCriterion("last_name >", value, "lastname");
			return this;
		}

		public Criteria andLastnameGreaterThanOrEqualTo(String value) {
			addCriterion("last_name >=", value, "lastname");
			return this;
		}

		public Criteria andLastnameLessThan(String value) {
			addCriterion("last_name <", value, "lastname");
			return this;
		}

		public Criteria andLastnameLessThanOrEqualTo(String value) {
			addCriterion("last_name <=", value, "lastname");
			return this;
		}

		public Criteria andLastnameLike(String value) {
			addCriterion("last_name like", value, "lastname");
			return this;
		}

		public Criteria andLastnameNotLike(String value) {
			addCriterion("last_name not like", value, "lastname");
			return this;
		}

		public Criteria andLastnameIn(List values) {
			addCriterion("last_name in", values, "lastname");
			return this;
		}

		public Criteria andLastnameNotIn(List values) {
			addCriterion("last_name not in", values, "lastname");
			return this;
		}

		public Criteria andLastnameBetween(String value1, String value2) {
			addCriterion("last_name between", value1, value2, "lastname");
			return this;
		}

		public Criteria andLastnameNotBetween(String value1, String value2) {
			addCriterion("last_name not between", value1, value2, "lastname");
			return this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return this;
		}

		public Criteria andAddressIn(List values) {
			addCriterion("address in", values, "address");
			return this;
		}

		public Criteria andAddressNotIn(List values) {
			addCriterion("address not in", values, "address");
			return this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return this;
		}

		public Criteria andCityIsNull() {
			addCriterion("city is null");
			return this;
		}

		public Criteria andCityIsNotNull() {
			addCriterion("city is not null");
			return this;
		}

		public Criteria andCityEqualTo(String value) {
			addCriterion("city =", value, "city");
			return this;
		}

		public Criteria andCityNotEqualTo(String value) {
			addCriterion("city <>", value, "city");
			return this;
		}

		public Criteria andCityGreaterThan(String value) {
			addCriterion("city >", value, "city");
			return this;
		}

		public Criteria andCityGreaterThanOrEqualTo(String value) {
			addCriterion("city >=", value, "city");
			return this;
		}

		public Criteria andCityLessThan(String value) {
			addCriterion("city <", value, "city");
			return this;
		}

		public Criteria andCityLessThanOrEqualTo(String value) {
			addCriterion("city <=", value, "city");
			return this;
		}

		public Criteria andCityLike(String value) {
			addCriterion("city like", value, "city");
			return this;
		}

		public Criteria andCityNotLike(String value) {
			addCriterion("city not like", value, "city");
			return this;
		}

		public Criteria andCityIn(List values) {
			addCriterion("city in", values, "city");
			return this;
		}

		public Criteria andCityNotIn(List values) {
			addCriterion("city not in", values, "city");
			return this;
		}

		public Criteria andCityBetween(String value1, String value2) {
			addCriterion("city between", value1, value2, "city");
			return this;
		}

		public Criteria andCityNotBetween(String value1, String value2) {
			addCriterion("city not between", value1, value2, "city");
			return this;
		}

		public Criteria andProvinceIsNull() {
			addCriterion("province is null");
			return this;
		}

		public Criteria andProvinceIsNotNull() {
			addCriterion("province is not null");
			return this;
		}

		public Criteria andProvinceEqualTo(String value) {
			addCriterion("province =", value, "province");
			return this;
		}

		public Criteria andProvinceNotEqualTo(String value) {
			addCriterion("province <>", value, "province");
			return this;
		}

		public Criteria andProvinceGreaterThan(String value) {
			addCriterion("province >", value, "province");
			return this;
		}

		public Criteria andProvinceGreaterThanOrEqualTo(String value) {
			addCriterion("province >=", value, "province");
			return this;
		}

		public Criteria andProvinceLessThan(String value) {
			addCriterion("province <", value, "province");
			return this;
		}

		public Criteria andProvinceLessThanOrEqualTo(String value) {
			addCriterion("province <=", value, "province");
			return this;
		}

		public Criteria andProvinceLike(String value) {
			addCriterion("province like", value, "province");
			return this;
		}

		public Criteria andProvinceNotLike(String value) {
			addCriterion("province not like", value, "province");
			return this;
		}

		public Criteria andProvinceIn(List values) {
			addCriterion("province in", values, "province");
			return this;
		}

		public Criteria andProvinceNotIn(List values) {
			addCriterion("province not in", values, "province");
			return this;
		}

		public Criteria andProvinceBetween(String value1, String value2) {
			addCriterion("province between", value1, value2, "province");
			return this;
		}

		public Criteria andProvinceNotBetween(String value1, String value2) {
			addCriterion("province not between", value1, value2, "province");
			return this;
		}

		public Criteria andCountryIsNull() {
			addCriterion("country is null");
			return this;
		}

		public Criteria andCountryIsNotNull() {
			addCriterion("country is not null");
			return this;
		}

		public Criteria andCountryEqualTo(String value) {
			addCriterion("country =", value, "country");
			return this;
		}

		public Criteria andCountryNotEqualTo(String value) {
			addCriterion("country <>", value, "country");
			return this;
		}

		public Criteria andCountryGreaterThan(String value) {
			addCriterion("country >", value, "country");
			return this;
		}

		public Criteria andCountryGreaterThanOrEqualTo(String value) {
			addCriterion("country >=", value, "country");
			return this;
		}

		public Criteria andCountryLessThan(String value) {
			addCriterion("country <", value, "country");
			return this;
		}

		public Criteria andCountryLessThanOrEqualTo(String value) {
			addCriterion("country <=", value, "country");
			return this;
		}

		public Criteria andCountryLike(String value) {
			addCriterion("country like", value, "country");
			return this;
		}

		public Criteria andCountryNotLike(String value) {
			addCriterion("country not like", value, "country");
			return this;
		}

		public Criteria andCountryIn(List values) {
			addCriterion("country in", values, "country");
			return this;
		}

		public Criteria andCountryNotIn(List values) {
			addCriterion("country not in", values, "country");
			return this;
		}

		public Criteria andCountryBetween(String value1, String value2) {
			addCriterion("country between", value1, value2, "country");
			return this;
		}

		public Criteria andCountryNotBetween(String value1, String value2) {
			addCriterion("country not between", value1, value2, "country");
			return this;
		}

		public Criteria andPostalcodeIsNull() {
			addCriterion("postal_code is null");
			return this;
		}

		public Criteria andPostalcodeIsNotNull() {
			addCriterion("postal_code is not null");
			return this;
		}

		public Criteria andPostalcodeEqualTo(String value) {
			addCriterion("postal_code =", value, "postalcode");
			return this;
		}

		public Criteria andPostalcodeNotEqualTo(String value) {
			addCriterion("postal_code <>", value, "postalcode");
			return this;
		}

		public Criteria andPostalcodeGreaterThan(String value) {
			addCriterion("postal_code >", value, "postalcode");
			return this;
		}

		public Criteria andPostalcodeGreaterThanOrEqualTo(String value) {
			addCriterion("postal_code >=", value, "postalcode");
			return this;
		}

		public Criteria andPostalcodeLessThan(String value) {
			addCriterion("postal_code <", value, "postalcode");
			return this;
		}

		public Criteria andPostalcodeLessThanOrEqualTo(String value) {
			addCriterion("postal_code <=", value, "postalcode");
			return this;
		}

		public Criteria andPostalcodeLike(String value) {
			addCriterion("postal_code like", value, "postalcode");
			return this;
		}

		public Criteria andPostalcodeNotLike(String value) {
			addCriterion("postal_code not like", value, "postalcode");
			return this;
		}

		public Criteria andPostalcodeIn(List values) {
			addCriterion("postal_code in", values, "postalcode");
			return this;
		}

		public Criteria andPostalcodeNotIn(List values) {
			addCriterion("postal_code not in", values, "postalcode");
			return this;
		}

		public Criteria andPostalcodeBetween(String value1, String value2) {
			addCriterion("postal_code between", value1, value2, "postalcode");
			return this;
		}

		public Criteria andPostalcodeNotBetween(String value1, String value2) {
			addCriterion("postal_code not between", value1, value2,
					"postalcode");
			return this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return this;
		}

		public Criteria andEmailIn(List values) {
			addCriterion("email in", values, "email");
			return this;
		}

		public Criteria andEmailNotIn(List values) {
			addCriterion("email not in", values, "email");
			return this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return this;
		}

		public Criteria andPhonenumberIsNull() {
			addCriterion("phone_number is null");
			return this;
		}

		public Criteria andPhonenumberIsNotNull() {
			addCriterion("phone_number is not null");
			return this;
		}

		public Criteria andPhonenumberEqualTo(String value) {
			addCriterion("phone_number =", value, "phonenumber");
			return this;
		}

		public Criteria andPhonenumberNotEqualTo(String value) {
			addCriterion("phone_number <>", value, "phonenumber");
			return this;
		}

		public Criteria andPhonenumberGreaterThan(String value) {
			addCriterion("phone_number >", value, "phonenumber");
			return this;
		}

		public Criteria andPhonenumberGreaterThanOrEqualTo(String value) {
			addCriterion("phone_number >=", value, "phonenumber");
			return this;
		}

		public Criteria andPhonenumberLessThan(String value) {
			addCriterion("phone_number <", value, "phonenumber");
			return this;
		}

		public Criteria andPhonenumberLessThanOrEqualTo(String value) {
			addCriterion("phone_number <=", value, "phonenumber");
			return this;
		}

		public Criteria andPhonenumberLike(String value) {
			addCriterion("phone_number like", value, "phonenumber");
			return this;
		}

		public Criteria andPhonenumberNotLike(String value) {
			addCriterion("phone_number not like", value, "phonenumber");
			return this;
		}

		public Criteria andPhonenumberIn(List values) {
			addCriterion("phone_number in", values, "phonenumber");
			return this;
		}

		public Criteria andPhonenumberNotIn(List values) {
			addCriterion("phone_number not in", values, "phonenumber");
			return this;
		}

		public Criteria andPhonenumberBetween(String value1, String value2) {
			addCriterion("phone_number between", value1, value2, "phonenumber");
			return this;
		}

		public Criteria andPhonenumberNotBetween(String value1, String value2) {
			addCriterion("phone_number not between", value1, value2,
					"phonenumber");
			return this;
		}

		public Criteria andWebsiteIsNull() {
			addCriterion("website is null");
			return this;
		}

		public Criteria andWebsiteIsNotNull() {
			addCriterion("website is not null");
			return this;
		}

		public Criteria andWebsiteEqualTo(String value) {
			addCriterion("website =", value, "website");
			return this;
		}

		public Criteria andWebsiteNotEqualTo(String value) {
			addCriterion("website <>", value, "website");
			return this;
		}

		public Criteria andWebsiteGreaterThan(String value) {
			addCriterion("website >", value, "website");
			return this;
		}

		public Criteria andWebsiteGreaterThanOrEqualTo(String value) {
			addCriterion("website >=", value, "website");
			return this;
		}

		public Criteria andWebsiteLessThan(String value) {
			addCriterion("website <", value, "website");
			return this;
		}

		public Criteria andWebsiteLessThanOrEqualTo(String value) {
			addCriterion("website <=", value, "website");
			return this;
		}

		public Criteria andWebsiteLike(String value) {
			addCriterion("website like", value, "website");
			return this;
		}

		public Criteria andWebsiteNotLike(String value) {
			addCriterion("website not like", value, "website");
			return this;
		}

		public Criteria andWebsiteIn(List values) {
			addCriterion("website in", values, "website");
			return this;
		}

		public Criteria andWebsiteNotIn(List values) {
			addCriterion("website not in", values, "website");
			return this;
		}

		public Criteria andWebsiteBetween(String value1, String value2) {
			addCriterion("website between", value1, value2, "website");
			return this;
		}

		public Criteria andWebsiteNotBetween(String value1, String value2) {
			addCriterion("website not between", value1, value2, "website");
			return this;
		}

		public Criteria andWebsitetitleIsNull() {
			addCriterion("website_title is null");
			return this;
		}

		public Criteria andWebsitetitleIsNotNull() {
			addCriterion("website_title is not null");
			return this;
		}

		public Criteria andWebsitetitleEqualTo(String value) {
			addCriterion("website_title =", value, "websitetitle");
			return this;
		}

		public Criteria andWebsitetitleNotEqualTo(String value) {
			addCriterion("website_title <>", value, "websitetitle");
			return this;
		}

		public Criteria andWebsitetitleGreaterThan(String value) {
			addCriterion("website_title >", value, "websitetitle");
			return this;
		}

		public Criteria andWebsitetitleGreaterThanOrEqualTo(String value) {
			addCriterion("website_title >=", value, "websitetitle");
			return this;
		}

		public Criteria andWebsitetitleLessThan(String value) {
			addCriterion("website_title <", value, "websitetitle");
			return this;
		}

		public Criteria andWebsitetitleLessThanOrEqualTo(String value) {
			addCriterion("website_title <=", value, "websitetitle");
			return this;
		}

		public Criteria andWebsitetitleLike(String value) {
			addCriterion("website_title like", value, "websitetitle");
			return this;
		}

		public Criteria andWebsitetitleNotLike(String value) {
			addCriterion("website_title not like", value, "websitetitle");
			return this;
		}

		public Criteria andWebsitetitleIn(List values) {
			addCriterion("website_title in", values, "websitetitle");
			return this;
		}

		public Criteria andWebsitetitleNotIn(List values) {
			addCriterion("website_title not in", values, "websitetitle");
			return this;
		}

		public Criteria andWebsitetitleBetween(String value1, String value2) {
			addCriterion("website_title between", value1, value2,
					"websitetitle");
			return this;
		}

		public Criteria andWebsitetitleNotBetween(String value1, String value2) {
			addCriterion("website_title not between", value1, value2,
					"websitetitle");
			return this;
		}

		public Criteria andPasswordhintIsNull() {
			addCriterion("password_hint is null");
			return this;
		}

		public Criteria andPasswordhintIsNotNull() {
			addCriterion("password_hint is not null");
			return this;
		}

		public Criteria andPasswordhintEqualTo(String value) {
			addCriterion("password_hint =", value, "passwordhint");
			return this;
		}

		public Criteria andPasswordhintNotEqualTo(String value) {
			addCriterion("password_hint <>", value, "passwordhint");
			return this;
		}

		public Criteria andPasswordhintGreaterThan(String value) {
			addCriterion("password_hint >", value, "passwordhint");
			return this;
		}

		public Criteria andPasswordhintGreaterThanOrEqualTo(String value) {
			addCriterion("password_hint >=", value, "passwordhint");
			return this;
		}

		public Criteria andPasswordhintLessThan(String value) {
			addCriterion("password_hint <", value, "passwordhint");
			return this;
		}

		public Criteria andPasswordhintLessThanOrEqualTo(String value) {
			addCriterion("password_hint <=", value, "passwordhint");
			return this;
		}

		public Criteria andPasswordhintLike(String value) {
			addCriterion("password_hint like", value, "passwordhint");
			return this;
		}

		public Criteria andPasswordhintNotLike(String value) {
			addCriterion("password_hint not like", value, "passwordhint");
			return this;
		}

		public Criteria andPasswordhintIn(List values) {
			addCriterion("password_hint in", values, "passwordhint");
			return this;
		}

		public Criteria andPasswordhintNotIn(List values) {
			addCriterion("password_hint not in", values, "passwordhint");
			return this;
		}

		public Criteria andPasswordhintBetween(String value1, String value2) {
			addCriterion("password_hint between", value1, value2,
					"passwordhint");
			return this;
		}

		public Criteria andPasswordhintNotBetween(String value1, String value2) {
			addCriterion("password_hint not between", value1, value2,
					"passwordhint");
			return this;
		}

		public Criteria andAccountenabledIsNull() {
			addCriterion("account_enabled is null");
			return this;
		}

		public Criteria andAccountenabledIsNotNull() {
			addCriterion("account_enabled is not null");
			return this;
		}

		public Criteria andAccountenabledEqualTo(String value) {
			addCriterion("account_enabled =", value, "accountenabled");
			return this;
		}

		public Criteria andAccountenabledNotEqualTo(String value) {
			addCriterion("account_enabled <>", value, "accountenabled");
			return this;
		}

		public Criteria andAccountenabledGreaterThan(String value) {
			addCriterion("account_enabled >", value, "accountenabled");
			return this;
		}

		public Criteria andAccountenabledGreaterThanOrEqualTo(String value) {
			addCriterion("account_enabled >=", value, "accountenabled");
			return this;
		}

		public Criteria andAccountenabledLessThan(String value) {
			addCriterion("account_enabled <", value, "accountenabled");
			return this;
		}

		public Criteria andAccountenabledLessThanOrEqualTo(String value) {
			addCriterion("account_enabled <=", value, "accountenabled");
			return this;
		}

		public Criteria andAccountenabledLike(String value) {
			addCriterion("account_enabled like", value, "accountenabled");
			return this;
		}

		public Criteria andAccountenabledNotLike(String value) {
			addCriterion("account_enabled not like", value, "accountenabled");
			return this;
		}

		public Criteria andAccountenabledIn(List values) {
			addCriterion("account_enabled in", values, "accountenabled");
			return this;
		}

		public Criteria andAccountenabledNotIn(List values) {
			addCriterion("account_enabled not in", values, "accountenabled");
			return this;
		}

		public Criteria andAccountenabledBetween(String value1, String value2) {
			addCriterion("account_enabled between", value1, value2,
					"accountenabled");
			return this;
		}

		public Criteria andAccountenabledNotBetween(String value1, String value2) {
			addCriterion("account_enabled not between", value1, value2,
					"accountenabled");
			return this;
		}

		public Criteria andAccountexpiredIsNull() {
			addCriterion("account_expired is null");
			return this;
		}

		public Criteria andAccountexpiredIsNotNull() {
			addCriterion("account_expired is not null");
			return this;
		}

		public Criteria andAccountexpiredEqualTo(String value) {
			addCriterion("account_expired =", value, "accountexpired");
			return this;
		}

		public Criteria andAccountexpiredNotEqualTo(String value) {
			addCriterion("account_expired <>", value, "accountexpired");
			return this;
		}

		public Criteria andAccountexpiredGreaterThan(String value) {
			addCriterion("account_expired >", value, "accountexpired");
			return this;
		}

		public Criteria andAccountexpiredGreaterThanOrEqualTo(String value) {
			addCriterion("account_expired >=", value, "accountexpired");
			return this;
		}

		public Criteria andAccountexpiredLessThan(String value) {
			addCriterion("account_expired <", value, "accountexpired");
			return this;
		}

		public Criteria andAccountexpiredLessThanOrEqualTo(String value) {
			addCriterion("account_expired <=", value, "accountexpired");
			return this;
		}

		public Criteria andAccountexpiredLike(String value) {
			addCriterion("account_expired like", value, "accountexpired");
			return this;
		}

		public Criteria andAccountexpiredNotLike(String value) {
			addCriterion("account_expired not like", value, "accountexpired");
			return this;
		}

		public Criteria andAccountexpiredIn(List values) {
			addCriterion("account_expired in", values, "accountexpired");
			return this;
		}

		public Criteria andAccountexpiredNotIn(List values) {
			addCriterion("account_expired not in", values, "accountexpired");
			return this;
		}

		public Criteria andAccountexpiredBetween(String value1, String value2) {
			addCriterion("account_expired between", value1, value2,
					"accountexpired");
			return this;
		}

		public Criteria andAccountexpiredNotBetween(String value1, String value2) {
			addCriterion("account_expired not between", value1, value2,
					"accountexpired");
			return this;
		}

		public Criteria andAccountlockedIsNull() {
			addCriterion("account_locked is null");
			return this;
		}

		public Criteria andAccountlockedIsNotNull() {
			addCriterion("account_locked is not null");
			return this;
		}

		public Criteria andAccountlockedEqualTo(String value) {
			addCriterion("account_locked =", value, "accountlocked");
			return this;
		}

		public Criteria andAccountlockedNotEqualTo(String value) {
			addCriterion("account_locked <>", value, "accountlocked");
			return this;
		}

		public Criteria andAccountlockedGreaterThan(String value) {
			addCriterion("account_locked >", value, "accountlocked");
			return this;
		}

		public Criteria andAccountlockedGreaterThanOrEqualTo(String value) {
			addCriterion("account_locked >=", value, "accountlocked");
			return this;
		}

		public Criteria andAccountlockedLessThan(String value) {
			addCriterion("account_locked <", value, "accountlocked");
			return this;
		}

		public Criteria andAccountlockedLessThanOrEqualTo(String value) {
			addCriterion("account_locked <=", value, "accountlocked");
			return this;
		}

		public Criteria andAccountlockedLike(String value) {
			addCriterion("account_locked like", value, "accountlocked");
			return this;
		}

		public Criteria andAccountlockedNotLike(String value) {
			addCriterion("account_locked not like", value, "accountlocked");
			return this;
		}

		public Criteria andAccountlockedIn(List values) {
			addCriterion("account_locked in", values, "accountlocked");
			return this;
		}

		public Criteria andAccountlockedNotIn(List values) {
			addCriterion("account_locked not in", values, "accountlocked");
			return this;
		}

		public Criteria andAccountlockedBetween(String value1, String value2) {
			addCriterion("account_locked between", value1, value2,
					"accountlocked");
			return this;
		}

		public Criteria andAccountlockedNotBetween(String value1, String value2) {
			addCriterion("account_locked not between", value1, value2,
					"accountlocked");
			return this;
		}

		public Criteria andCredentialsexpiredIsNull() {
			addCriterion("credentials_expired is null");
			return this;
		}

		public Criteria andCredentialsexpiredIsNotNull() {
			addCriterion("credentials_expired is not null");
			return this;
		}

		public Criteria andCredentialsexpiredEqualTo(String value) {
			addCriterion("credentials_expired =", value, "credentialsexpired");
			return this;
		}

		public Criteria andCredentialsexpiredNotEqualTo(String value) {
			addCriterion("credentials_expired <>", value, "credentialsexpired");
			return this;
		}

		public Criteria andCredentialsexpiredGreaterThan(String value) {
			addCriterion("credentials_expired >", value, "credentialsexpired");
			return this;
		}

		public Criteria andCredentialsexpiredGreaterThanOrEqualTo(String value) {
			addCriterion("credentials_expired >=", value, "credentialsexpired");
			return this;
		}

		public Criteria andCredentialsexpiredLessThan(String value) {
			addCriterion("credentials_expired <", value, "credentialsexpired");
			return this;
		}

		public Criteria andCredentialsexpiredLessThanOrEqualTo(String value) {
			addCriterion("credentials_expired <=", value, "credentialsexpired");
			return this;
		}

		public Criteria andCredentialsexpiredLike(String value) {
			addCriterion("credentials_expired like", value,
					"credentialsexpired");
			return this;
		}

		public Criteria andCredentialsexpiredNotLike(String value) {
			addCriterion("credentials_expired not like", value,
					"credentialsexpired");
			return this;
		}

		public Criteria andCredentialsexpiredIn(List values) {
			addCriterion("credentials_expired in", values, "credentialsexpired");
			return this;
		}

		public Criteria andCredentialsexpiredNotIn(List values) {
			addCriterion("credentials_expired not in", values,
					"credentialsexpired");
			return this;
		}

		public Criteria andCredentialsexpiredBetween(String value1,
				String value2) {
			addCriterion("credentials_expired between", value1, value2,
					"credentialsexpired");
			return this;
		}

		public Criteria andCredentialsexpiredNotBetween(String value1,
				String value2) {
			addCriterion("credentials_expired not between", value1, value2,
					"credentialsexpired");
			return this;
		}

		public Criteria andImageIsNull() {
			addCriterion("image is null");
			return this;
		}

		public Criteria andImageIsNotNull() {
			addCriterion("image is not null");
			return this;
		}

		public Criteria andImageEqualTo(String value) {
			addCriterion("image =", value, "image");
			return this;
		}

		public Criteria andImageNotEqualTo(String value) {
			addCriterion("image <>", value, "image");
			return this;
		}

		public Criteria andImageGreaterThan(String value) {
			addCriterion("image >", value, "image");
			return this;
		}

		public Criteria andImageGreaterThanOrEqualTo(String value) {
			addCriterion("image >=", value, "image");
			return this;
		}

		public Criteria andImageLessThan(String value) {
			addCriterion("image <", value, "image");
			return this;
		}

		public Criteria andImageLessThanOrEqualTo(String value) {
			addCriterion("image <=", value, "image");
			return this;
		}

		public Criteria andImageLike(String value) {
			addCriterion("image like", value, "image");
			return this;
		}

		public Criteria andImageNotLike(String value) {
			addCriterion("image not like", value, "image");
			return this;
		}

		public Criteria andImageIn(List values) {
			addCriterion("image in", values, "image");
			return this;
		}

		public Criteria andImageNotIn(List values) {
			addCriterion("image not in", values, "image");
			return this;
		}

		public Criteria andImageBetween(String value1, String value2) {
			addCriterion("image between", value1, value2, "image");
			return this;
		}

		public Criteria andImageNotBetween(String value1, String value2) {
			addCriterion("image not between", value1, value2, "image");
			return this;
		}
	}
}