package com.tamuvii.model;

public class AppUser {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.id
	 * @ibatorgenerated
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.username
	 * @ibatorgenerated
	 */
	private String username;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.version
	 * @ibatorgenerated
	 */
	private Integer version;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.password
	 * @ibatorgenerated
	 */
	private String password;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.first_name
	 * @ibatorgenerated
	 */
	private String firstname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.last_name
	 * @ibatorgenerated
	 */
	private String lastname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.address
	 * @ibatorgenerated
	 */
	private String address;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.city
	 * @ibatorgenerated
	 */
	private String city;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.province
	 * @ibatorgenerated
	 */
	private String province;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.country
	 * @ibatorgenerated
	 */
	private String country;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.postal_code
	 * @ibatorgenerated
	 */
	private String postalcode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.email
	 * @ibatorgenerated
	 */
	private String email;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.phone_number
	 * @ibatorgenerated
	 */
	private String phonenumber;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.website
	 * @ibatorgenerated
	 */
	private String website;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.website_title
	 * @ibatorgenerated
	 */
	private String websitetitle;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.password_hint
	 * @ibatorgenerated
	 */
	private String passwordhint;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.account_enabled
	 * @ibatorgenerated
	 */
	private String accountenabled;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.account_expired
	 * @ibatorgenerated
	 */
	private String accountexpired;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.account_locked
	 * @ibatorgenerated
	 */
	private String accountlocked;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.credentials_expired
	 * @ibatorgenerated
	 */
	private String credentialsexpired;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_user.image
	 * @ibatorgenerated
	 */
	private String image;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.id
	 * @return  the value of app_user.id
	 * @ibatorgenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.id
	 * @param id  the value for app_user.id
	 * @ibatorgenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.username
	 * @return  the value of app_user.username
	 * @ibatorgenerated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.username
	 * @param username  the value for app_user.username
	 * @ibatorgenerated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.version
	 * @return  the value of app_user.version
	 * @ibatorgenerated
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.version
	 * @param version  the value for app_user.version
	 * @ibatorgenerated
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.password
	 * @return  the value of app_user.password
	 * @ibatorgenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.password
	 * @param password  the value for app_user.password
	 * @ibatorgenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.first_name
	 * @return  the value of app_user.first_name
	 * @ibatorgenerated
	 */
	public String getFirstname() {
		return firstname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.first_name
	 * @param firstname  the value for app_user.first_name
	 * @ibatorgenerated
	 */
	public void setFirstname(String firstname) {
		this.firstname = firstname == null ? null : firstname.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.last_name
	 * @return  the value of app_user.last_name
	 * @ibatorgenerated
	 */
	public String getLastname() {
		return lastname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.last_name
	 * @param lastname  the value for app_user.last_name
	 * @ibatorgenerated
	 */
	public void setLastname(String lastname) {
		this.lastname = lastname == null ? null : lastname.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.address
	 * @return  the value of app_user.address
	 * @ibatorgenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.address
	 * @param address  the value for app_user.address
	 * @ibatorgenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.city
	 * @return  the value of app_user.city
	 * @ibatorgenerated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.city
	 * @param city  the value for app_user.city
	 * @ibatorgenerated
	 */
	public void setCity(String city) {
		this.city = city == null ? null : city.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.province
	 * @return  the value of app_user.province
	 * @ibatorgenerated
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.province
	 * @param province  the value for app_user.province
	 * @ibatorgenerated
	 */
	public void setProvince(String province) {
		this.province = province == null ? null : province.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.country
	 * @return  the value of app_user.country
	 * @ibatorgenerated
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.country
	 * @param country  the value for app_user.country
	 * @ibatorgenerated
	 */
	public void setCountry(String country) {
		this.country = country == null ? null : country.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.postal_code
	 * @return  the value of app_user.postal_code
	 * @ibatorgenerated
	 */
	public String getPostalcode() {
		return postalcode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.postal_code
	 * @param postalcode  the value for app_user.postal_code
	 * @ibatorgenerated
	 */
	public void setPostalcode(String postalcode) {
		this.postalcode = postalcode == null ? null : postalcode.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.email
	 * @return  the value of app_user.email
	 * @ibatorgenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.email
	 * @param email  the value for app_user.email
	 * @ibatorgenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.phone_number
	 * @return  the value of app_user.phone_number
	 * @ibatorgenerated
	 */
	public String getPhonenumber() {
		return phonenumber;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.phone_number
	 * @param phonenumber  the value for app_user.phone_number
	 * @ibatorgenerated
	 */
	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber == null ? null : phonenumber.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.website
	 * @return  the value of app_user.website
	 * @ibatorgenerated
	 */
	public String getWebsite() {
		return website;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.website
	 * @param website  the value for app_user.website
	 * @ibatorgenerated
	 */
	public void setWebsite(String website) {
		this.website = website == null ? null : website.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.website_title
	 * @return  the value of app_user.website_title
	 * @ibatorgenerated
	 */
	public String getWebsitetitle() {
		return websitetitle;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.website_title
	 * @param websitetitle  the value for app_user.website_title
	 * @ibatorgenerated
	 */
	public void setWebsitetitle(String websitetitle) {
		this.websitetitle = websitetitle == null ? null : websitetitle.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.password_hint
	 * @return  the value of app_user.password_hint
	 * @ibatorgenerated
	 */
	public String getPasswordhint() {
		return passwordhint;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.password_hint
	 * @param passwordhint  the value for app_user.password_hint
	 * @ibatorgenerated
	 */
	public void setPasswordhint(String passwordhint) {
		this.passwordhint = passwordhint == null ? null : passwordhint.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.account_enabled
	 * @return  the value of app_user.account_enabled
	 * @ibatorgenerated
	 */
	public String getAccountenabled() {
		return accountenabled;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.account_enabled
	 * @param accountenabled  the value for app_user.account_enabled
	 * @ibatorgenerated
	 */
	public void setAccountenabled(String accountenabled) {
		this.accountenabled = accountenabled == null ? null : accountenabled
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.account_expired
	 * @return  the value of app_user.account_expired
	 * @ibatorgenerated
	 */
	public String getAccountexpired() {
		return accountexpired;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.account_expired
	 * @param accountexpired  the value for app_user.account_expired
	 * @ibatorgenerated
	 */
	public void setAccountexpired(String accountexpired) {
		this.accountexpired = accountexpired == null ? null : accountexpired
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.account_locked
	 * @return  the value of app_user.account_locked
	 * @ibatorgenerated
	 */
	public String getAccountlocked() {
		return accountlocked;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.account_locked
	 * @param accountlocked  the value for app_user.account_locked
	 * @ibatorgenerated
	 */
	public void setAccountlocked(String accountlocked) {
		this.accountlocked = accountlocked == null ? null : accountlocked
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.credentials_expired
	 * @return  the value of app_user.credentials_expired
	 * @ibatorgenerated
	 */
	public String getCredentialsexpired() {
		return credentialsexpired;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.credentials_expired
	 * @param credentialsexpired  the value for app_user.credentials_expired
	 * @ibatorgenerated
	 */
	public void setCredentialsexpired(String credentialsexpired) {
		this.credentialsexpired = credentialsexpired == null ? null
				: credentialsexpired.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_user.image
	 * @return  the value of app_user.image
	 * @ibatorgenerated
	 */
	public String getImage() {
		return image;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_user.image
	 * @param image  the value for app_user.image
	 * @ibatorgenerated
	 */
	public void setImage(String image) {
		this.image = image == null ? null : image.trim();
	}
}