package com.tamuvii.model;

public class Config {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column config.configKey
     *
     * @ibatorgenerated
     */
    private String configkey;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column config.configValue
     *
     * @ibatorgenerated
     */
    private String configvalue;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column config.configKey
     *
     * @return the value of config.configKey
     *
     * @ibatorgenerated
     */
    public String getConfigkey() {
        return configkey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column config.configKey
     *
     * @param configkey the value for config.configKey
     *
     * @ibatorgenerated
     */
    public void setConfigkey(String configkey) {
        this.configkey = configkey == null ? null : configkey.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column config.configValue
     *
     * @return the value of config.configValue
     *
     * @ibatorgenerated
     */
    public String getConfigvalue() {
        return configvalue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column config.configValue
     *
     * @param configvalue the value for config.configValue
     *
     * @ibatorgenerated
     */
    public void setConfigvalue(String configvalue) {
        this.configvalue = configvalue == null ? null : configvalue.trim();
    }
}