package com.tamuvii.model;

public class Director {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column director.director
     *
     * @ibatorgenerated
     */
    private Integer director;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column director.name
     *
     * @ibatorgenerated
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column director.surname
     *
     * @ibatorgenerated
     */
    private String surname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column director.aka
     *
     * @ibatorgenerated
     */
    private String aka;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column director.director
     *
     * @return the value of director.director
     *
     * @ibatorgenerated
     */
    public Integer getDirector() {
        return director;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column director.director
     *
     * @param director the value for director.director
     *
     * @ibatorgenerated
     */
    public void setDirector(Integer director) {
        this.director = director;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column director.name
     *
     * @return the value of director.name
     *
     * @ibatorgenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column director.name
     *
     * @param name the value for director.name
     *
     * @ibatorgenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column director.surname
     *
     * @return the value of director.surname
     *
     * @ibatorgenerated
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column director.surname
     *
     * @param surname the value for director.surname
     *
     * @ibatorgenerated
     */
    public void setSurname(String surname) {
        this.surname = surname == null ? null : surname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column director.aka
     *
     * @return the value of director.aka
     *
     * @ibatorgenerated
     */
    public String getAka() {
        return aka;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column director.aka
     *
     * @param aka the value for director.aka
     *
     * @ibatorgenerated
     */
    public void setAka(String aka) {
        this.aka = aka == null ? null : aka.trim();
    }
}