package com.tamuvii.model;

import java.io.Serializable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/** 
 * Object mapping for hibernate-handled table: localized_movie_data.
 * @author autogenerated
 */

@Entity
@Table(name = "localized_movie_data", catalog = "tamuvii")
public  class LocalizedMovieData implements Cloneable, Serializable {

	/** Serial Version UID. */
	private static final long serialVersionUID = -559009208L;


	/** Field mapping. */
	private String id;
	/** Field mapping. */
	private String locale;
	/** Field mapping. */
	private Movie movie;
	/** Field mapping. */
	private String plot;
	/** Field mapping. */
	private String title;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public LocalizedMovieData() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public LocalizedMovieData(String id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param id String object;
	 * @param locale String object;
	 */
	public LocalizedMovieData(String id, String locale) {

		this.id = id;
		this.locale = locale;
	}
	
 


    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
    @Id 
	@Column( name = "localized_movie_data", nullable = false, length = 45  )
	public String getId() {
		return this.id;
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final String id) {
		this.id = id;
	}


    /**
     * Return the value associated with the column: locale.
	 * @return A String object (this.locale)
	 */
	@Column( nullable = false, length = 5  )
	public String getLocale() {
		return this.locale;
	}
	

  
    /**  
     * Set the value related to the column: locale.
	 * @param locale the locale value you wish to set
	 */
	public void setLocale(final String locale) {
		this.locale = locale;
	}


    /**
     * Return the value associated with the column: movie.
	 * @return A Movie object (this.movie)
	 */
	
	@ManyToOne( cascade = CascadeType.ALL )
	@JoinColumn(name = "movie", nullable = true  )
	public Movie getMovie() {
		return this.movie;
	}
	

  
    /**  
     * Set the value related to the column: movie.
	 * @param movie the movie value you wish to set
	 */
	public void setMovie(final Movie movie) {
		this.movie = movie;
	}


    /**
     * Return the value associated with the column: plot.
	 * @return A String object (this.plot)
	 */
	@Column( length = 16777215  )
	public String getPlot() {
		return this.plot;
	}
	

  
    /**  
     * Set the value related to the column: plot.
	 * @param plot the plot value you wish to set
	 */
	public void setPlot(final String plot) {
		this.plot = plot;
	}


    /**
     * Return the value associated with the column: title.
	 * @return A String object (this.title)
	 */
	@Column( length = 200  )
	public String getTitle() {
		return this.title;
	}
	

  
    /**  
     * Set the value related to the column: title.
	 * @param title the title value you wish to set
	 */
	public void setTitle(final String title) {
		this.title = title;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public LocalizedMovieData clone() throws CloneNotSupportedException {
		super.clone();  // keep hierarchy
        final LocalizedMovieData copy = new LocalizedMovieData();

		copy.setId(this.getId());
		copy.setLocale(this.getLocale());
		copy.setMovie(this.getMovie());
		copy.setPlot(this.getPlot());
		copy.setTitle(this.getTitle());
		return copy;
	}


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("id: " + this.id + ", ");
		sb.append("locale: " + this.locale + ", ");
		sb.append("plot: " + this.plot + ", ");
		sb.append("title: " + this.title);
		return sb.toString();		
	}


	
	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		if ( this == aThat ) {
			 return true;
		}
		if ((aThat == null) || ( !(aThat instanceof LocalizedMovieData))) {
			 return false;
		}
		final LocalizedMovieData that = (LocalizedMovieData) aThat;
		
		return (((this.id == null) && (that.id == null)) 
			   || (this.id != null  && this.id.equals(that.id)))
			   && 
			(((this.locale == null) && (that.locale == null)) 
			   || (this.locale != null  && this.locale.equals(that.locale)))
			   && 
			(((this.movie == null) && (that.movie == null)) 
			   || (this.movie != null  && this.movie.equals(that.movie)))
			   && 
			(((this.plot == null) && (that.plot == null)) 
			   || (this.plot != null  && this.plot.equals(that.plot)))
			   && 
			(((this.title == null) && (that.title == null)) 
			   || (this.title != null  && this.title.equals(that.title)))
			   ;
	}


	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		int result = 0;
		result = 1000003 * result + (this.id == null ? 0 : this.id.hashCode());
		result = 1000003 * result + (this.locale == null ? 0 : this.locale.hashCode());
		result = 1000003 * result + (this.plot == null ? 0 : this.plot.hashCode());
		result = 1000003 * result + (this.title == null ? 0 : this.title.hashCode());

		return result;  
	}
}