package com.tamuvii.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MovieExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table movie
	 * @ibatorgenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table movie
	 * @ibatorgenerated
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	public MovieExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	protected MovieExample(MovieExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table movie
	 * @ibatorgenerated
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table movie
	 * @ibatorgenerated
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andMovieIsNull() {
			addCriterion("movie is null");
			return this;
		}

		public Criteria andMovieIsNotNull() {
			addCriterion("movie is not null");
			return this;
		}

		public Criteria andMovieEqualTo(Integer value) {
			addCriterion("movie =", value, "movie");
			return this;
		}

		public Criteria andMovieNotEqualTo(Integer value) {
			addCriterion("movie <>", value, "movie");
			return this;
		}

		public Criteria andMovieGreaterThan(Integer value) {
			addCriterion("movie >", value, "movie");
			return this;
		}

		public Criteria andMovieGreaterThanOrEqualTo(Integer value) {
			addCriterion("movie >=", value, "movie");
			return this;
		}

		public Criteria andMovieLessThan(Integer value) {
			addCriterion("movie <", value, "movie");
			return this;
		}

		public Criteria andMovieLessThanOrEqualTo(Integer value) {
			addCriterion("movie <=", value, "movie");
			return this;
		}

		public Criteria andMovieIn(List values) {
			addCriterion("movie in", values, "movie");
			return this;
		}

		public Criteria andMovieNotIn(List values) {
			addCriterion("movie not in", values, "movie");
			return this;
		}

		public Criteria andMovieBetween(Integer value1, Integer value2) {
			addCriterion("movie between", value1, value2, "movie");
			return this;
		}

		public Criteria andMovieNotBetween(Integer value1, Integer value2) {
			addCriterion("movie not between", value1, value2, "movie");
			return this;
		}

		public Criteria andDurationIsNull() {
			addCriterion("duration is null");
			return this;
		}

		public Criteria andDurationIsNotNull() {
			addCriterion("duration is not null");
			return this;
		}

		public Criteria andDurationEqualTo(String value) {
			addCriterion("duration =", value, "duration");
			return this;
		}

		public Criteria andDurationNotEqualTo(String value) {
			addCriterion("duration <>", value, "duration");
			return this;
		}

		public Criteria andDurationGreaterThan(String value) {
			addCriterion("duration >", value, "duration");
			return this;
		}

		public Criteria andDurationGreaterThanOrEqualTo(String value) {
			addCriterion("duration >=", value, "duration");
			return this;
		}

		public Criteria andDurationLessThan(String value) {
			addCriterion("duration <", value, "duration");
			return this;
		}

		public Criteria andDurationLessThanOrEqualTo(String value) {
			addCriterion("duration <=", value, "duration");
			return this;
		}

		public Criteria andDurationLike(String value) {
			addCriterion("duration like", value, "duration");
			return this;
		}

		public Criteria andDurationNotLike(String value) {
			addCriterion("duration not like", value, "duration");
			return this;
		}

		public Criteria andDurationIn(List values) {
			addCriterion("duration in", values, "duration");
			return this;
		}

		public Criteria andDurationNotIn(List values) {
			addCriterion("duration not in", values, "duration");
			return this;
		}

		public Criteria andDurationBetween(String value1, String value2) {
			addCriterion("duration between", value1, value2, "duration");
			return this;
		}

		public Criteria andDurationNotBetween(String value1, String value2) {
			addCriterion("duration not between", value1, value2, "duration");
			return this;
		}

		public Criteria andOriginaltitleIsNull() {
			addCriterion("original_title is null");
			return this;
		}

		public Criteria andOriginaltitleIsNotNull() {
			addCriterion("original_title is not null");
			return this;
		}

		public Criteria andOriginaltitleEqualTo(String value) {
			addCriterion("original_title =", value, "originaltitle");
			return this;
		}

		public Criteria andOriginaltitleNotEqualTo(String value) {
			addCriterion("original_title <>", value, "originaltitle");
			return this;
		}

		public Criteria andOriginaltitleGreaterThan(String value) {
			addCriterion("original_title >", value, "originaltitle");
			return this;
		}

		public Criteria andOriginaltitleGreaterThanOrEqualTo(String value) {
			addCriterion("original_title >=", value, "originaltitle");
			return this;
		}

		public Criteria andOriginaltitleLessThan(String value) {
			addCriterion("original_title <", value, "originaltitle");
			return this;
		}

		public Criteria andOriginaltitleLessThanOrEqualTo(String value) {
			addCriterion("original_title <=", value, "originaltitle");
			return this;
		}

		public Criteria andOriginaltitleLike(String value) {
			addCriterion("original_title like", value, "originaltitle");
			return this;
		}

		public Criteria andOriginaltitleNotLike(String value) {
			addCriterion("original_title not like", value, "originaltitle");
			return this;
		}

		public Criteria andOriginaltitleIn(List values) {
			addCriterion("original_title in", values, "originaltitle");
			return this;
		}

		public Criteria andOriginaltitleNotIn(List values) {
			addCriterion("original_title not in", values, "originaltitle");
			return this;
		}

		public Criteria andOriginaltitleBetween(String value1, String value2) {
			addCriterion("original_title between", value1, value2,
					"originaltitle");
			return this;
		}

		public Criteria andOriginaltitleNotBetween(String value1, String value2) {
			addCriterion("original_title not between", value1, value2,
					"originaltitle");
			return this;
		}

		public Criteria andDirectorIsNull() {
			addCriterion("director is null");
			return this;
		}

		public Criteria andDirectorIsNotNull() {
			addCriterion("director is not null");
			return this;
		}

		public Criteria andDirectorEqualTo(Integer value) {
			addCriterion("director =", value, "director");
			return this;
		}

		public Criteria andDirectorNotEqualTo(Integer value) {
			addCriterion("director <>", value, "director");
			return this;
		}

		public Criteria andDirectorGreaterThan(Integer value) {
			addCriterion("director >", value, "director");
			return this;
		}

		public Criteria andDirectorGreaterThanOrEqualTo(Integer value) {
			addCriterion("director >=", value, "director");
			return this;
		}

		public Criteria andDirectorLessThan(Integer value) {
			addCriterion("director <", value, "director");
			return this;
		}

		public Criteria andDirectorLessThanOrEqualTo(Integer value) {
			addCriterion("director <=", value, "director");
			return this;
		}

		public Criteria andDirectorIn(List values) {
			addCriterion("director in", values, "director");
			return this;
		}

		public Criteria andDirectorNotIn(List values) {
			addCriterion("director not in", values, "director");
			return this;
		}

		public Criteria andDirectorBetween(Integer value1, Integer value2) {
			addCriterion("director between", value1, value2, "director");
			return this;
		}

		public Criteria andDirectorNotBetween(Integer value1, Integer value2) {
			addCriterion("director not between", value1, value2, "director");
			return this;
		}

		public Criteria andReleasedateIsNull() {
			addCriterion("release_date is null");
			return this;
		}

		public Criteria andReleasedateIsNotNull() {
			addCriterion("release_date is not null");
			return this;
		}

		public Criteria andReleasedateEqualTo(Date value) {
			addCriterion("release_date =", value, "releasedate");
			return this;
		}

		public Criteria andReleasedateNotEqualTo(Date value) {
			addCriterion("release_date <>", value, "releasedate");
			return this;
		}

		public Criteria andReleasedateGreaterThan(Date value) {
			addCriterion("release_date >", value, "releasedate");
			return this;
		}

		public Criteria andReleasedateGreaterThanOrEqualTo(Date value) {
			addCriterion("release_date >=", value, "releasedate");
			return this;
		}

		public Criteria andReleasedateLessThan(Date value) {
			addCriterion("release_date <", value, "releasedate");
			return this;
		}

		public Criteria andReleasedateLessThanOrEqualTo(Date value) {
			addCriterion("release_date <=", value, "releasedate");
			return this;
		}

		public Criteria andReleasedateIn(List values) {
			addCriterion("release_date in", values, "releasedate");
			return this;
		}

		public Criteria andReleasedateNotIn(List values) {
			addCriterion("release_date not in", values, "releasedate");
			return this;
		}

		public Criteria andReleasedateBetween(Date value1, Date value2) {
			addCriterion("release_date between", value1, value2, "releasedate");
			return this;
		}

		public Criteria andReleasedateNotBetween(Date value1, Date value2) {
			addCriterion("release_date not between", value1, value2,
					"releasedate");
			return this;
		}

		public Criteria andOriginalplotIsNull() {
			addCriterion("original_plot is null");
			return this;
		}

		public Criteria andOriginalplotIsNotNull() {
			addCriterion("original_plot is not null");
			return this;
		}

		public Criteria andOriginalplotEqualTo(String value) {
			addCriterion("original_plot =", value, "originalplot");
			return this;
		}

		public Criteria andOriginalplotNotEqualTo(String value) {
			addCriterion("original_plot <>", value, "originalplot");
			return this;
		}

		public Criteria andOriginalplotGreaterThan(String value) {
			addCriterion("original_plot >", value, "originalplot");
			return this;
		}

		public Criteria andOriginalplotGreaterThanOrEqualTo(String value) {
			addCriterion("original_plot >=", value, "originalplot");
			return this;
		}

		public Criteria andOriginalplotLessThan(String value) {
			addCriterion("original_plot <", value, "originalplot");
			return this;
		}

		public Criteria andOriginalplotLessThanOrEqualTo(String value) {
			addCriterion("original_plot <=", value, "originalplot");
			return this;
		}

		public Criteria andOriginalplotLike(String value) {
			addCriterion("original_plot like", value, "originalplot");
			return this;
		}

		public Criteria andOriginalplotNotLike(String value) {
			addCriterion("original_plot not like", value, "originalplot");
			return this;
		}

		public Criteria andOriginalplotIn(List values) {
			addCriterion("original_plot in", values, "originalplot");
			return this;
		}

		public Criteria andOriginalplotNotIn(List values) {
			addCriterion("original_plot not in", values, "originalplot");
			return this;
		}

		public Criteria andOriginalplotBetween(String value1, String value2) {
			addCriterion("original_plot between", value1, value2,
					"originalplot");
			return this;
		}

		public Criteria andOriginalplotNotBetween(String value1, String value2) {
			addCriterion("original_plot not between", value1, value2,
					"originalplot");
			return this;
		}

		public Criteria andOriginalimageIsNull() {
			addCriterion("original_image is null");
			return this;
		}

		public Criteria andOriginalimageIsNotNull() {
			addCriterion("original_image is not null");
			return this;
		}

		public Criteria andOriginalimageEqualTo(String value) {
			addCriterion("original_image =", value, "originalimage");
			return this;
		}

		public Criteria andOriginalimageNotEqualTo(String value) {
			addCriterion("original_image <>", value, "originalimage");
			return this;
		}

		public Criteria andOriginalimageGreaterThan(String value) {
			addCriterion("original_image >", value, "originalimage");
			return this;
		}

		public Criteria andOriginalimageGreaterThanOrEqualTo(String value) {
			addCriterion("original_image >=", value, "originalimage");
			return this;
		}

		public Criteria andOriginalimageLessThan(String value) {
			addCriterion("original_image <", value, "originalimage");
			return this;
		}

		public Criteria andOriginalimageLessThanOrEqualTo(String value) {
			addCriterion("original_image <=", value, "originalimage");
			return this;
		}

		public Criteria andOriginalimageLike(String value) {
			addCriterion("original_image like", value, "originalimage");
			return this;
		}

		public Criteria andOriginalimageNotLike(String value) {
			addCriterion("original_image not like", value, "originalimage");
			return this;
		}

		public Criteria andOriginalimageIn(List values) {
			addCriterion("original_image in", values, "originalimage");
			return this;
		}

		public Criteria andOriginalimageNotIn(List values) {
			addCriterion("original_image not in", values, "originalimage");
			return this;
		}

		public Criteria andOriginalimageBetween(String value1, String value2) {
			addCriterion("original_image between", value1, value2,
					"originalimage");
			return this;
		}

		public Criteria andOriginalimageNotBetween(String value1, String value2) {
			addCriterion("original_image not between", value1, value2,
					"originalimage");
			return this;
		}

		public Criteria andOriginalcountryIsNull() {
			addCriterion("original_country is null");
			return this;
		}

		public Criteria andOriginalcountryIsNotNull() {
			addCriterion("original_country is not null");
			return this;
		}

		public Criteria andOriginalcountryEqualTo(String value) {
			addCriterion("original_country =", value, "originalcountry");
			return this;
		}

		public Criteria andOriginalcountryNotEqualTo(String value) {
			addCriterion("original_country <>", value, "originalcountry");
			return this;
		}

		public Criteria andOriginalcountryGreaterThan(String value) {
			addCriterion("original_country >", value, "originalcountry");
			return this;
		}

		public Criteria andOriginalcountryGreaterThanOrEqualTo(String value) {
			addCriterion("original_country >=", value, "originalcountry");
			return this;
		}

		public Criteria andOriginalcountryLessThan(String value) {
			addCriterion("original_country <", value, "originalcountry");
			return this;
		}

		public Criteria andOriginalcountryLessThanOrEqualTo(String value) {
			addCriterion("original_country <=", value, "originalcountry");
			return this;
		}

		public Criteria andOriginalcountryLike(String value) {
			addCriterion("original_country like", value, "originalcountry");
			return this;
		}

		public Criteria andOriginalcountryNotLike(String value) {
			addCriterion("original_country not like", value, "originalcountry");
			return this;
		}

		public Criteria andOriginalcountryIn(List values) {
			addCriterion("original_country in", values, "originalcountry");
			return this;
		}

		public Criteria andOriginalcountryNotIn(List values) {
			addCriterion("original_country not in", values, "originalcountry");
			return this;
		}

		public Criteria andOriginalcountryBetween(String value1, String value2) {
			addCriterion("original_country between", value1, value2,
					"originalcountry");
			return this;
		}

		public Criteria andOriginalcountryNotBetween(String value1,
				String value2) {
			addCriterion("original_country not between", value1, value2,
					"originalcountry");
			return this;
		}

		public Criteria andOriginaltrailerIsNull() {
			addCriterion("original_trailer is null");
			return this;
		}

		public Criteria andOriginaltrailerIsNotNull() {
			addCriterion("original_trailer is not null");
			return this;
		}

		public Criteria andOriginaltrailerEqualTo(String value) {
			addCriterion("original_trailer =", value, "originaltrailer");
			return this;
		}

		public Criteria andOriginaltrailerNotEqualTo(String value) {
			addCriterion("original_trailer <>", value, "originaltrailer");
			return this;
		}

		public Criteria andOriginaltrailerGreaterThan(String value) {
			addCriterion("original_trailer >", value, "originaltrailer");
			return this;
		}

		public Criteria andOriginaltrailerGreaterThanOrEqualTo(String value) {
			addCriterion("original_trailer >=", value, "originaltrailer");
			return this;
		}

		public Criteria andOriginaltrailerLessThan(String value) {
			addCriterion("original_trailer <", value, "originaltrailer");
			return this;
		}

		public Criteria andOriginaltrailerLessThanOrEqualTo(String value) {
			addCriterion("original_trailer <=", value, "originaltrailer");
			return this;
		}

		public Criteria andOriginaltrailerLike(String value) {
			addCriterion("original_trailer like", value, "originaltrailer");
			return this;
		}

		public Criteria andOriginaltrailerNotLike(String value) {
			addCriterion("original_trailer not like", value, "originaltrailer");
			return this;
		}

		public Criteria andOriginaltrailerIn(List values) {
			addCriterion("original_trailer in", values, "originaltrailer");
			return this;
		}

		public Criteria andOriginaltrailerNotIn(List values) {
			addCriterion("original_trailer not in", values, "originaltrailer");
			return this;
		}

		public Criteria andOriginaltrailerBetween(String value1, String value2) {
			addCriterion("original_trailer between", value1, value2,
					"originaltrailer");
			return this;
		}

		public Criteria andOriginaltrailerNotBetween(String value1,
				String value2) {
			addCriterion("original_trailer not between", value1, value2,
					"originaltrailer");
			return this;
		}
	}
}