package com.tamuvii.model;

import java.util.Date;

public class Movie {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movie.movie
	 * @ibatorgenerated
	 */
	private Integer movie;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movie.duration
	 * @ibatorgenerated
	 */
	private String duration;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movie.original_title
	 * @ibatorgenerated
	 */
	private String originaltitle;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movie.director
	 * @ibatorgenerated
	 */
	private Integer director;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movie.release_date
	 * @ibatorgenerated
	 */
	private Date releasedate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movie.original_plot
	 * @ibatorgenerated
	 */
	private String originalplot;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movie.original_image
	 * @ibatorgenerated
	 */
	private String originalimage;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movie.original_country
	 * @ibatorgenerated
	 */
	private String originalcountry;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column movie.original_trailer
	 * @ibatorgenerated
	 */
	private String originaltrailer;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movie.movie
	 * @return  the value of movie.movie
	 * @ibatorgenerated
	 */
	public Integer getMovie() {
		return movie;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movie.movie
	 * @param movie  the value for movie.movie
	 * @ibatorgenerated
	 */
	public void setMovie(Integer movie) {
		this.movie = movie;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movie.duration
	 * @return  the value of movie.duration
	 * @ibatorgenerated
	 */
	public String getDuration() {
		return duration;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movie.duration
	 * @param duration  the value for movie.duration
	 * @ibatorgenerated
	 */
	public void setDuration(String duration) {
		this.duration = duration == null ? null : duration.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movie.original_title
	 * @return  the value of movie.original_title
	 * @ibatorgenerated
	 */
	public String getOriginaltitle() {
		return originaltitle;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movie.original_title
	 * @param originaltitle  the value for movie.original_title
	 * @ibatorgenerated
	 */
	public void setOriginaltitle(String originaltitle) {
		this.originaltitle = originaltitle == null ? null : originaltitle
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movie.director
	 * @return  the value of movie.director
	 * @ibatorgenerated
	 */
	public Integer getDirector() {
		return director;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movie.director
	 * @param director  the value for movie.director
	 * @ibatorgenerated
	 */
	public void setDirector(Integer director) {
		this.director = director;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movie.release_date
	 * @return  the value of movie.release_date
	 * @ibatorgenerated
	 */
	public Date getReleasedate() {
		return releasedate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movie.release_date
	 * @param releasedate  the value for movie.release_date
	 * @ibatorgenerated
	 */
	public void setReleasedate(Date releasedate) {
		this.releasedate = releasedate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movie.original_plot
	 * @return  the value of movie.original_plot
	 * @ibatorgenerated
	 */
	public String getOriginalplot() {
		return originalplot;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movie.original_plot
	 * @param originalplot  the value for movie.original_plot
	 * @ibatorgenerated
	 */
	public void setOriginalplot(String originalplot) {
		this.originalplot = originalplot == null ? null : originalplot.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movie.original_image
	 * @return  the value of movie.original_image
	 * @ibatorgenerated
	 */
	public String getOriginalimage() {
		return originalimage;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movie.original_image
	 * @param originalimage  the value for movie.original_image
	 * @ibatorgenerated
	 */
	public void setOriginalimage(String originalimage) {
		this.originalimage = originalimage == null ? null : originalimage
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movie.original_country
	 * @return  the value of movie.original_country
	 * @ibatorgenerated
	 */
	public String getOriginalcountry() {
		return originalcountry;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movie.original_country
	 * @param originalcountry  the value for movie.original_country
	 * @ibatorgenerated
	 */
	public void setOriginalcountry(String originalcountry) {
		this.originalcountry = originalcountry == null ? null : originalcountry
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column movie.original_trailer
	 * @return  the value of movie.original_trailer
	 * @ibatorgenerated
	 */
	public String getOriginaltrailer() {
		return originaltrailer;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column movie.original_trailer
	 * @param originaltrailer  the value for movie.original_trailer
	 * @ibatorgenerated
	 */
	public void setOriginaltrailer(String originaltrailer) {
		this.originaltrailer = originaltrailer == null ? null : originaltrailer
				.trim();
	}
}