package com.tamuvii.model;

import java.util.Date;

public class UserToUser extends UserToUserKey {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user_to_user.friend
	 * @ibatorgenerated
	 */
	private Integer friend;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user_to_user.date_added
	 * @ibatorgenerated
	 */
	private Date dateadded;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user_to_user.friend
	 * @return  the value of user_to_user.friend
	 * @ibatorgenerated
	 */
	public Integer getFriend() {
		return friend;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user_to_user.friend
	 * @param friend  the value for user_to_user.friend
	 * @ibatorgenerated
	 */
	public void setFriend(Integer friend) {
		this.friend = friend;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user_to_user.date_added
	 * @return  the value of user_to_user.date_added
	 * @ibatorgenerated
	 */
	public Date getDateadded() {
		return dateadded;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user_to_user.date_added
	 * @param dateadded  the value for user_to_user.date_added
	 * @ibatorgenerated
	 */
	public void setDateadded(Date dateadded) {
		this.dateadded = dateadded;
	}
}