package com.tamuvii.model;

import java.util.Date;

public class UserReviewVote extends UserReviewVoteKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_review_vote.date_voted
     *
     * @ibatorgenerated
     */
    private Date datevoted;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_review_vote.date_voted
     *
     * @return the value of user_review_vote.date_voted
     *
     * @ibatorgenerated
     */
    public Date getDatevoted() {
        return datevoted;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_review_vote.date_voted
     *
     * @param datevoted the value for user_review_vote.date_voted
     *
     * @ibatorgenerated
     */
    public void setDatevoted(Date datevoted) {
        this.datevoted = datevoted;
    }
}