package com.tamuvii.model;

public class UserToMovieKey {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user_to_movie.movie
	 * @ibatorgenerated
	 */
	private Integer movie;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user_to_movie.username
	 * @ibatorgenerated
	 */
	private String username;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user_to_movie.movie
	 * @return  the value of user_to_movie.movie
	 * @ibatorgenerated
	 */
	public Integer getMovie() {
		return movie;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user_to_movie.movie
	 * @param movie  the value for user_to_movie.movie
	 * @ibatorgenerated
	 */
	public void setMovie(Integer movie) {
		this.movie = movie;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user_to_movie.username
	 * @return  the value of user_to_movie.username
	 * @ibatorgenerated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user_to_movie.username
	 * @param username  the value for user_to_movie.username
	 * @ibatorgenerated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}
}