package com.tamuvii.model;

public class UserReviewVoteKey {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user_review_vote.review
	 * @ibatorgenerated
	 */
	private Integer review;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user_review_vote.username
	 * @ibatorgenerated
	 */
	private String username;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user_review_vote.review
	 * @return  the value of user_review_vote.review
	 * @ibatorgenerated
	 */
	public Integer getReview() {
		return review;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user_review_vote.review
	 * @param review  the value for user_review_vote.review
	 * @ibatorgenerated
	 */
	public void setReview(Integer review) {
		this.review = review;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user_review_vote.username
	 * @return  the value of user_review_vote.username
	 * @ibatorgenerated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user_review_vote.username
	 * @param username  the value for user_review_vote.username
	 * @ibatorgenerated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}
}