package com.tamuvii.model;

public class UserToUser extends UserToUserKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_to_user.friend
     *
     * @ibatorgenerated
     */
    private Integer friend;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_to_user.friend
     *
     * @return the value of user_to_user.friend
     *
     * @ibatorgenerated
     */
    public Integer getFriend() {
        return friend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_to_user.friend
     *
     * @param friend the value for user_to_user.friend
     *
     * @ibatorgenerated
     */
    public void setFriend(Integer friend) {
        this.friend = friend;
    }
}