package com.tamuvii.model;

import java.util.Date;

public class Visit {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column visit.visit
     *
     * @ibatorgenerated
     */
    private Integer visit;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column visit.visited
     *
     * @ibatorgenerated
     */
    private String visited;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column visit.visitor
     *
     * @ibatorgenerated
     */
    private String visitor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column visit.date_visit
     *
     * @ibatorgenerated
     */
    private Date datevisit;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column visit.visit
     *
     * @return the value of visit.visit
     *
     * @ibatorgenerated
     */
    public Integer getVisit() {
        return visit;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column visit.visit
     *
     * @param visit the value for visit.visit
     *
     * @ibatorgenerated
     */
    public void setVisit(Integer visit) {
        this.visit = visit;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column visit.visited
     *
     * @return the value of visit.visited
     *
     * @ibatorgenerated
     */
    public String getVisited() {
        return visited;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column visit.visited
     *
     * @param visited the value for visit.visited
     *
     * @ibatorgenerated
     */
    public void setVisited(String visited) {
        this.visited = visited == null ? null : visited.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column visit.visitor
     *
     * @return the value of visit.visitor
     *
     * @ibatorgenerated
     */
    public String getVisitor() {
        return visitor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column visit.visitor
     *
     * @param visitor the value for visit.visitor
     *
     * @ibatorgenerated
     */
    public void setVisitor(String visitor) {
        this.visitor = visitor == null ? null : visitor.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column visit.date_visit
     *
     * @return the value of visit.date_visit
     *
     * @ibatorgenerated
     */
    public Date getDatevisit() {
        return datevisit;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column visit.date_visit
     *
     * @param datevisit the value for visit.date_visit
     *
     * @ibatorgenerated
     */
    public void setDatevisit(Date datevisit) {
        this.datevisit = datevisit;
    }
}