package com.tamuvii.eventdispatcher;

public enum TamuviiEventType {
	ORDER_CONFIRMATION,CONTRACT_CANCELLATION,CONTRACT_MODIFICATION,CONTRACT_HISTORY_VIEW_REQUEST,
	SENSIBLE_DATA_UPDATE_REQUEST,NON_SENSIBLE_DATA_UPDATE_REQUEST,
	BRANCH_ADDITION,BRANCH_DELETION,BRANCH_MODIFICATION,LIGHT_PORTAL_SUBSCRIPTION
}