package com.tamuvii.dao.impl;

import java.io.Serializable;

import org.springframework.stereotype.Repository;

import com.tamuvii.dao.ActorDao;
import com.tamuvii.dao.hibernate.GenericDaoHibernate;
import com.tamuvii.model.Actor;

/**
 * DAO for table: Actor.
 * @author autogenerated
 */
@Repository
public class ActorDaoImpl extends GenericDaoHibernate<Actor, Serializable> implements ActorDao {
	
	/** Constructor method. */
		public ActorDaoImpl() {
			super(Actor.class);
		}
	}

