package com.tamuvii.dao.impl;

import com.tamuvii.dao.AppUserDAO;
import com.tamuvii.model.AppUser;
import com.tamuvii.model.AppUserExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AppUserDAOImpl extends SqlMapClientDaoSupport implements AppUserDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table app_user
     *
     * @ibatorgenerated
     */
    public AppUserDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table app_user
     *
     * @ibatorgenerated
     */
    public int countByExample(AppUserExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("app_user.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table app_user
     *
     * @ibatorgenerated
     */
    public int deleteByExample(AppUserExample example) {
        int rows = getSqlMapClientTemplate().delete("app_user.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table app_user
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        AppUser key = new AppUser();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("app_user.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table app_user
     *
     * @ibatorgenerated
     */
    public void insert(AppUser record) {
        getSqlMapClientTemplate().insert("app_user.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table app_user
     *
     * @ibatorgenerated
     */
    public void insertSelective(AppUser record) {
        getSqlMapClientTemplate().insert("app_user.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table app_user
     *
     * @ibatorgenerated
     */
    public List selectByExample(AppUserExample example) {
        List list = getSqlMapClientTemplate().queryForList("app_user.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table app_user
     *
     * @ibatorgenerated
     */
    public AppUser selectByPrimaryKey(Integer id) {
        AppUser key = new AppUser();
        key.setId(id);
        AppUser record = (AppUser) getSqlMapClientTemplate().queryForObject("app_user.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table app_user
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(AppUser record, AppUserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("app_user.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table app_user
     *
     * @ibatorgenerated
     */
    public int updateByExample(AppUser record, AppUserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("app_user.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table app_user
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(AppUser record) {
        int rows = getSqlMapClientTemplate().update("app_user.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table app_user
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(AppUser record) {
        int rows = getSqlMapClientTemplate().update("app_user.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table app_user
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends AppUserExample {
        private Object record;

        public UpdateByExampleParms(Object record, AppUserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}