package com.tamuvii.dao.impl;

import com.tamuvii.dao.ConfigDAO;
import com.tamuvii.model.Config;
import com.tamuvii.model.ConfigExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ConfigDAOImpl extends SqlMapClientDaoSupport implements ConfigDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table config
     *
     * @ibatorgenerated
     */
    public ConfigDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table config
     *
     * @ibatorgenerated
     */
    public int countByExample(ConfigExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("config.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table config
     *
     * @ibatorgenerated
     */
    public int deleteByExample(ConfigExample example) {
        int rows = getSqlMapClientTemplate().delete("config.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table config
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(String configkey) {
        Config key = new Config();
        key.setConfigkey(configkey);
        int rows = getSqlMapClientTemplate().delete("config.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table config
     *
     * @ibatorgenerated
     */
    public void insert(Config record) {
        getSqlMapClientTemplate().insert("config.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table config
     *
     * @ibatorgenerated
     */
    public void insertSelective(Config record) {
        getSqlMapClientTemplate().insert("config.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table config
     *
     * @ibatorgenerated
     */
    public List selectByExample(ConfigExample example) {
        List list = getSqlMapClientTemplate().queryForList("config.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table config
     *
     * @ibatorgenerated
     */
    public Config selectByPrimaryKey(String configkey) {
        Config key = new Config();
        key.setConfigkey(configkey);
        Config record = (Config) getSqlMapClientTemplate().queryForObject("config.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table config
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Config record, ConfigExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("config.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table config
     *
     * @ibatorgenerated
     */
    public int updateByExample(Config record, ConfigExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("config.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table config
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Config record) {
        int rows = getSqlMapClientTemplate().update("config.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table config
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Config record) {
        int rows = getSqlMapClientTemplate().update("config.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table config
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends ConfigExample {
        private Object record;

        public UpdateByExampleParms(Object record, ConfigExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}