package com.tamuvii.dao.impl;

import org.springframework.stereotype.Repository;

import com.tamuvii.dao.DirectorDao;
import com.tamuvii.dao.hibernate.GenericDaoHibernate;
import com.tamuvii.model.Director;

/**
 * DAO for table: Director.
 * @author autogenerated
 */
@Repository
public class DirectorDaoImpl extends GenericDaoHibernate<Director, Integer> implements DirectorDao {
	
	/** Constructor method. */
		public DirectorDaoImpl() {
			super(Director.class);
		}
	}

