package com.tamuvii.dao.impl;

import com.tamuvii.dao.DirectorDAO;
import com.tamuvii.model.Director;
import com.tamuvii.model.DirectorExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DirectorDAOImpl extends SqlMapClientDaoSupport implements DirectorDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	public DirectorDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	public int countByExample(DirectorExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"director.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	public int deleteByExample(DirectorExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"director.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer director) {
		Director key = new Director();
		key.setDirector(director);
		int rows = getSqlMapClientTemplate().delete(
				"director.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	public void insert(Director record) {
		getSqlMapClientTemplate().insert("director.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	public void insertSelective(Director record) {
		getSqlMapClientTemplate().insert(
				"director.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	public List selectByExample(DirectorExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"director.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	public Director selectByPrimaryKey(Integer director) {
		Director key = new Director();
		key.setDirector(director);
		Director record = (Director) getSqlMapClientTemplate().queryForObject(
				"director.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Director record, DirectorExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"director.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	public int updateByExample(Director record, DirectorExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"director.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Director record) {
		int rows = getSqlMapClientTemplate().update(
				"director.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table director
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Director record) {
		int rows = getSqlMapClientTemplate().update(
				"director.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table director
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends DirectorExample {
		private Object record;

		public UpdateByExampleParms(Object record, DirectorExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}