package com.tamuvii.dao.impl;

import org.springframework.stereotype.Repository;

import com.tamuvii.dao.MarkDao;
import com.tamuvii.dao.hibernate.GenericDaoHibernate;
import com.tamuvii.model.Mark;

/**
 * DAO for table: Mark.
 * @author autogenerated
 */
@Repository
public class MarkDaoImpl extends GenericDaoHibernate<Mark, String> implements MarkDao {
	
	/** Constructor method. */
		public MarkDaoImpl() {
			super(Mark.class);
		}
	}

