package com.tamuvii.dao.impl;

import java.io.Serializable;
import java.util.List;
import java.util.StringTokenizer;

import org.hibernate.Query;
import org.hibernate.Session;
import org.springframework.stereotype.Repository;

import com.tamuvii.dao.MovieDao;
import com.tamuvii.dao.hibernate.GenericDaoHibernate;
import com.tamuvii.model.Movie;

/**
 * DAO for table: Movie.
 * @author autogenerated
 */
@Repository
public class MovieDaoImpl extends GenericDaoHibernate<Movie, Serializable> implements MovieDao {
	
	/** Constructor method. */
		public MovieDaoImpl() {
			super(Movie.class);
		}

	@SuppressWarnings("unchecked")
	public List<Movie> findMovieByFilter(String filter) {
		String cleanedFilter = filter.replaceAll("\'", " ");
		if(cleanedFilter.trim().equals("")) 
			return null;
		
		Session session = getSession();
		StringTokenizer st = new StringTokenizer(cleanedFilter, " ");
		String firstToken = st.nextToken();
		
		
		String query = "SELECT m FROM Movie m WHERE (";
		query = query + "m.director.surname LIKE '%"+firstToken+"%' " +
		"OR m.director.name LIKE '%"+firstToken+"%' " +
		"OR m.originalTitle LIKE '%"+firstToken+"%' ";
		
		while(st.hasMoreTokens()) {
			String stringToken = st.nextToken();
			query = query + "m.director.surname LIKE '%"+stringToken+"%' " +
			"OR m.director.name LIKE '%"+stringToken+"%' " +
			"OR m.originalTitle LIKE '%"+stringToken+"%' ";
		}
					
		query = query + ") ORDER BY m.originalTitle ASC";
					
		Query q = session.createQuery(query);
		List<Movie> movies = q.list();
			
		return movies;
	}

}