package com.tamuvii.dao.impl;

import com.tamuvii.dao.MovieDAO;
import com.tamuvii.model.Movie;
import com.tamuvii.model.MovieExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MovieDAOImpl extends SqlMapClientDaoSupport implements MovieDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table movie
     *
     * @ibatorgenerated
     */
    public MovieDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table movie
     *
     * @ibatorgenerated
     */
    public int countByExample(MovieExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("movie.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table movie
     *
     * @ibatorgenerated
     */
    public int deleteByExample(MovieExample example) {
        int rows = getSqlMapClientTemplate().delete("movie.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table movie
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer movie) {
        Movie key = new Movie();
        key.setMovie(movie);
        int rows = getSqlMapClientTemplate().delete("movie.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table movie
     *
     * @ibatorgenerated
     */
    public void insert(Movie record) {
        getSqlMapClientTemplate().insert("movie.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table movie
     *
     * @ibatorgenerated
     */
    public void insertSelective(Movie record) {
        getSqlMapClientTemplate().insert("movie.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table movie
     *
     * @ibatorgenerated
     */
    public List selectByExample(MovieExample example) {
        List list = getSqlMapClientTemplate().queryForList("movie.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table movie
     *
     * @ibatorgenerated
     */
    public Movie selectByPrimaryKey(Integer movie) {
        Movie key = new Movie();
        key.setMovie(movie);
        Movie record = (Movie) getSqlMapClientTemplate().queryForObject("movie.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table movie
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Movie record, MovieExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("movie.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table movie
     *
     * @ibatorgenerated
     */
    public int updateByExample(Movie record, MovieExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("movie.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table movie
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Movie record) {
        int rows = getSqlMapClientTemplate().update("movie.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table movie
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Movie record) {
        int rows = getSqlMapClientTemplate().update("movie.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table movie
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends MovieExample {
        private Object record;

        public UpdateByExampleParms(Object record, MovieExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}