package com.tamuvii.dao.impl;

import com.tamuvii.dao.OpinionDAO;
import com.tamuvii.model.Opinion;
import com.tamuvii.model.OpinionExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OpinionDAOImpl extends SqlMapClientDaoSupport implements OpinionDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	public OpinionDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	public int countByExample(OpinionExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"opinion.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	public int deleteByExample(OpinionExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"opinion.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer opinion) {
		Opinion key = new Opinion();
		key.setOpinion(opinion);
		int rows = getSqlMapClientTemplate().delete(
				"opinion.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	public void insert(Opinion record) {
		getSqlMapClientTemplate().insert("opinion.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	public void insertSelective(Opinion record) {
		getSqlMapClientTemplate().insert(
				"opinion.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	public List selectByExample(OpinionExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"opinion.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	public Opinion selectByPrimaryKey(Integer opinion) {
		Opinion key = new Opinion();
		key.setOpinion(opinion);
		Opinion record = (Opinion) getSqlMapClientTemplate().queryForObject(
				"opinion.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Opinion record, OpinionExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"opinion.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	public int updateByExample(Opinion record, OpinionExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"opinion.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Opinion record) {
		int rows = getSqlMapClientTemplate().update(
				"opinion.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Opinion record) {
		int rows = getSqlMapClientTemplate().update(
				"opinion.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table opinion
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends OpinionExample {
		private Object record;

		public UpdateByExampleParms(Object record, OpinionExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}