package com.tamuvii.dao.impl;

import com.tamuvii.dao.ReviewDAO;
import com.tamuvii.model.Review;
import com.tamuvii.model.ReviewExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ReviewDAOImpl extends SqlMapClientDaoSupport implements ReviewDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	public ReviewDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	public int countByExample(ReviewExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"review.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	public int deleteByExample(ReviewExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"review.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer review) {
		Review key = new Review();
		key.setReview(review);
		int rows = getSqlMapClientTemplate().delete(
				"review.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	public void insert(Review record) {
		getSqlMapClientTemplate().insert("review.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	public void insertSelective(Review record) {
		getSqlMapClientTemplate().insert(
				"review.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	public List selectByExample(ReviewExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"review.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	public Review selectByPrimaryKey(Integer review) {
		Review key = new Review();
		key.setReview(review);
		Review record = (Review) getSqlMapClientTemplate().queryForObject(
				"review.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Review record, ReviewExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"review.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	public int updateByExample(Review record, ReviewExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"review.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Review record) {
		int rows = getSqlMapClientTemplate().update(
				"review.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table review
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Review record) {
		int rows = getSqlMapClientTemplate().update(
				"review.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table review
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends ReviewExample {
		private Object record;

		public UpdateByExampleParms(Object record, ReviewExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}