package com.tamuvii.dao.impl;

import java.io.Serializable;

import org.springframework.stereotype.Repository;

import com.tamuvii.dao.ReviewDao;
import com.tamuvii.dao.hibernate.GenericDaoHibernate;
import com.tamuvii.model.Review;

/**
 * DAO for table: Review.
 * @author autogenerated
 */
@Repository
public class ReviewDaoImpl extends GenericDaoHibernate<Review, Serializable> implements ReviewDao {
	
	/** Constructor method. */
		public ReviewDaoImpl() {
			super(Review.class);
		}
	}

