package com.tamuvii.dao.impl;

import org.springframework.stereotype.Repository;

import com.tamuvii.dao.TitleDao;
import com.tamuvii.dao.hibernate.GenericDaoHibernate;
import com.tamuvii.model.Title;

/**
 * DAO for table: Title.
 * @author autogenerated
 */
@Repository
public class TitleDaoImpl extends GenericDaoHibernate<Title, String> implements TitleDao {
	
	/** Constructor method. */
		public TitleDaoImpl() {
			super(Title.class);
		}
	}

