package com.tamuvii.dao.impl;

import com.tamuvii.dao.UserReviewVoteDAO;
import com.tamuvii.model.UserReviewVoteExample;
import com.tamuvii.model.UserReviewVoteKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.tamuvii.model.UserReviewVote;

public class UserReviewVoteDAOImpl extends SqlMapClientDaoSupport implements UserReviewVoteDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	public UserReviewVoteDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	public int countByExample(UserReviewVoteExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"user_review_vote.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	public int deleteByExample(UserReviewVoteExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"user_review_vote.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(UserReviewVoteKey key) {
		int rows = getSqlMapClientTemplate().delete(
				"user_review_vote.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	public void insert(UserReviewVote record) {
		getSqlMapClientTemplate().insert(
				"user_review_vote.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	public void insertSelective(UserReviewVote record) {
		getSqlMapClientTemplate().insert(
				"user_review_vote.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	public List selectByExample(UserReviewVoteExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"user_review_vote.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	public UserReviewVote selectByPrimaryKey(UserReviewVoteKey key) {
		UserReviewVote record = (UserReviewVote) getSqlMapClientTemplate()
				.queryForObject(
						"user_review_vote.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(UserReviewVote record,
			UserReviewVoteExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"user_review_vote.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	public int updateByExample(UserReviewVote record,
			UserReviewVoteExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"user_review_vote.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(UserReviewVote record) {
		int rows = getSqlMapClientTemplate().update(
				"user_review_vote.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(UserReviewVote record) {
		int rows = getSqlMapClientTemplate().update(
				"user_review_vote.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table user_review_vote
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends UserReviewVoteExample {
		private Object record;

		public UpdateByExampleParms(Object record, UserReviewVoteExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}