package com.tamuvii.dao.impl;

import com.tamuvii.dao.UserToMovieDAO;
import com.tamuvii.model.UserToMovie;
import com.tamuvii.model.UserToMovieExample;
import com.tamuvii.model.UserToMovieKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserToMovieDAOImpl extends SqlMapClientDaoSupport implements UserToMovieDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_to_movie
	 * @ibatorgenerated
	 */
	public UserToMovieDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_to_movie
	 * @ibatorgenerated
	 */
	public int countByExample(UserToMovieExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"user_to_movie.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_to_movie
	 * @ibatorgenerated
	 */
	public int deleteByExample(UserToMovieExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"user_to_movie.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_to_movie
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(UserToMovieKey key) {
		int rows = getSqlMapClientTemplate().delete(
				"user_to_movie.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_to_movie
	 * @ibatorgenerated
	 */
	public void insert(UserToMovie record) {
		getSqlMapClientTemplate().insert(
				"user_to_movie.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_to_movie
	 * @ibatorgenerated
	 */
	public void insertSelective(UserToMovie record) {
		getSqlMapClientTemplate().insert(
				"user_to_movie.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_to_movie
	 * @ibatorgenerated
	 */
	public List selectByExample(UserToMovieExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"user_to_movie.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_to_movie
	 * @ibatorgenerated
	 */
	public UserToMovie selectByPrimaryKey(UserToMovieKey key) {
		UserToMovie record = (UserToMovie) getSqlMapClientTemplate()
				.queryForObject(
						"user_to_movie.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_to_movie
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(UserToMovie record,
			UserToMovieExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"user_to_movie.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_to_movie
	 * @ibatorgenerated
	 */
	public int updateByExample(UserToMovie record, UserToMovieExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"user_to_movie.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_to_movie
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(UserToMovie record) {
		int rows = getSqlMapClientTemplate().update(
				"user_to_movie.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table user_to_movie
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(UserToMovie record) {
		int rows = getSqlMapClientTemplate().update(
				"user_to_movie.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table user_to_movie
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends UserToMovieExample {
		private Object record;

		public UpdateByExampleParms(Object record, UserToMovieExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}