package com.tamuvii.dao.impl;

import com.tamuvii.dao.VisitDAO;
import com.tamuvii.model.Visit;
import com.tamuvii.model.VisitExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class VisitDAOImpl extends SqlMapClientDaoSupport implements VisitDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table visit
     *
     * @ibatorgenerated
     */
    public VisitDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table visit
     *
     * @ibatorgenerated
     */
    public int countByExample(VisitExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("visit.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table visit
     *
     * @ibatorgenerated
     */
    public int deleteByExample(VisitExample example) {
        int rows = getSqlMapClientTemplate().delete("visit.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table visit
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer visit) {
        Visit key = new Visit();
        key.setVisit(visit);
        int rows = getSqlMapClientTemplate().delete("visit.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table visit
     *
     * @ibatorgenerated
     */
    public void insert(Visit record) {
        getSqlMapClientTemplate().insert("visit.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table visit
     *
     * @ibatorgenerated
     */
    public void insertSelective(Visit record) {
        getSqlMapClientTemplate().insert("visit.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table visit
     *
     * @ibatorgenerated
     */
    public List selectByExample(VisitExample example) {
        List list = getSqlMapClientTemplate().queryForList("visit.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table visit
     *
     * @ibatorgenerated
     */
    public Visit selectByPrimaryKey(Integer visit) {
        Visit key = new Visit();
        key.setVisit(visit);
        Visit record = (Visit) getSqlMapClientTemplate().queryForObject("visit.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table visit
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Visit record, VisitExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("visit.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table visit
     *
     * @ibatorgenerated
     */
    public int updateByExample(Visit record, VisitExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("visit.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table visit
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Visit record) {
        int rows = getSqlMapClientTemplate().update("visit.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table visit
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Visit record) {
        int rows = getSqlMapClientTemplate().update("visit.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table visit
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends VisitExample {
        private Object record;

        public UpdateByExampleParms(Object record, VisitExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}